function init(self)
	msg.post("@render:", "clear_color", { color = vmath.vector4(1, 1, 1, 0) } )
	msg.post(".", "acquire_input_focus")
end

local chal_status -- this is the status of the challenge. It is true if the challenge has been passed and false otherwise
local msg_chal = hash("chal")
function on_message(self, message_id, message, sender)
	if message_id == msg_chal then
		local node = gui.get_node("challenge")
		gui.set_text(node, message.c)
		chal_status = message.status
		node = gui.get_node("chal_but") -- I reused the node variable to accomodate the text on the challenge button
		if chal_status then
			gui.set_text(node, "TAP TO GET\nREWARD")
		else
			gui.set_text(node, "CHANGE\nCHALLENGE")
		end
	end
end

local touch = hash("touch")
function on_input(self, action_id, action)
	if action_id == touch and action.released then
		local node = gui.get_node("_chal_but")
		if gui.pick_node(node, action.x, action.y) then
			if chal_status then
				--give reward
			else
				msg.post("#challenge_test", "change_challenge")
			end
		end
	end
end