--[[local positions = {
	vmath.vector3(120, 800, 0),	vmath.vector3(520, 800, 0),	vmath.vector3(520, 800, 0),
	vmath.vector3(120, 600, 0),	vmath.vector3(520, 600, 0),	vmath.vector3(520, 600, 0),
	vmath.vector3(120, 400, 0),	vmath.vector3(520, 400, 0),	vmath.vector3(520, 400, 0)
	vmath.vector3(120, 200, 0),	vmath.vector3(520, 200, 0),	vmath.vector3(520, 200, 0)
}

local scale = vmath.vector3(0.8, 1.6, 1)
]]

local TouchFb = require("modules.animation")